<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Bu Handayani',
                'email' => 'handayani@gmail.com',
                'password' => '$2y$10$qFfHoXNDGYHJvnVCbZJjku2zB1QzWfi8jKWo8lQ7oiEDlJ5KfrAUS',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 21:56:35',
                'updated_at' => '2023-02-04 21:56:35',
                'regency' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Bu Mawar',
                'email' => 'mawarbu@gmail.com',
                'password' => '$2y$10$w/KbvqZJF0NQdmUzT3np/Opr32j9.v10/OUqwkZkFUxQvj1bBjaZy',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:05:18',
                'updated_at' => '2023-02-04 22:05:18',
                'regency' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Warung Makan Pak Joni',
                'email' => 'jonipak@gmail.com',
                'password' => '$2y$10$.P/5pF815XhnxALPSzO/0O6WKP2Ud/sWKkz5zQnRlMVwwWO/IPW9i',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:10:45',
                'updated_at' => '2023-02-04 22:10:45',
                'regency' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Warung Babi Guling Cahaya Bintang Tina',
                'email' => 'bintang@gmail.com',
                'password' => '$2y$10$q.ouWjIEXlPhEHGmxgi6HeUGB6WQAzcbjH8TIWmYN1GN5cTyWtdfC',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:13:47',
                'updated_at' => '2023-02-04 22:13:47',
                'regency' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Warung Bu Makan Babi Guling Bu Manis',
                'email' => 'bumanis@gmail.com',
                'password' => '$2y$10$pxUSfmzD5VUrLbbWDR6eIuN9c5zs9FMlPuFOGJFVDDAtVwJz3awBS',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:16:43',
                'updated_at' => '2023-02-04 22:16:43',
                'regency' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Warung Begeh Sari',
                'email' => 'begeh@gmail.com',
                'password' => '$2y$10$Dc9B5KOS3fZjhLehfUzUGuW7lUkTAeCCrdPR5JJE1CsyeRyrnkl8S',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:24:05',
                'updated_at' => '2023-02-04 22:24:05',
                'regency' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Pang Tiam',
                'email' => 'pangtiam@gmail.com',
                'password' => '$2y$10$0X33Rxftmmr7GBBGZnrzCuwiuNCdZi7Rbj4TqWPDnN/HmzNRK4bsS',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:28:38',
                'updated_at' => '2023-02-04 22:28:38',
                'regency' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Conato Bakery',
                'email' => 'conato@gmail.com',
                'password' => '$2y$10$2RKHeKjiikQ9x1P/Z/fEVOoBL7ZrL4vmkFUXG.FGmT/dB6bQ0RtCy',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:33:31',
                'updated_at' => '2023-02-04 22:33:31',
                'regency' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Purimas 3 Cake & Bakery',
                'email' => 'purimas3@gmail.com',
                'password' => '$2y$10$pDC9IZbjexp3akgfVTfYCOZXYvOi/AYi6vKPQDETD672jSuFla2h2',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:36:27',
                'updated_at' => '2023-02-04 22:36:27',
                'regency' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Valencia Bakery',
                'email' => 'valencia@gmail.com',
                'password' => '$2y$10$vQ/Uf5Z1exnOQzpUgYFfROWBK1U5bC1f96sO0nnAGYx5W1YayauXa',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:41:05',
                'updated_at' => '2023-02-04 22:41:05',
                'regency' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Sinta Trisnajayanti',
                'email' => 'sintatrisna@gmail.com',
                'password' => '$2y$10$9vvglY9OJjMplhxkOByMQOwcJb4GH7RPcIvLwqU0INxaWPYdw/tRi',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:52:08',
                'updated_at' => '2023-02-04 22:52:08',
                'regency' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Kadek Andre Suryana',
                'email' => 'andre17@gmail.com',
                'password' => '$2y$10$y2S/1STKTGyKEn5uczRM4OTD2U70NIxF4xsDZiCd/78kCS8yvcXbm',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:54:14',
                'updated_at' => '2023-02-04 22:54:14',
                'regency' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Alisya Putri',
                'email' => 'alisya@gmail.com',
                'password' => '$2y$10$c5IFyeqa7pXkgitfLYUKX.dHManvHzodERhNy3N7FlC6vjUEhEtL2',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:56:18',
                'updated_at' => '2023-02-04 22:56:18',
                'regency' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Agung Alit',
                'email' => 'gungalit@gmail.com',
                'password' => '$2y$10$/F/dg7tqZBh6FO0e9tqZF.bXup/DDiuLxA9z3bDJWq1GC/F/BGmaS',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 22:59:08',
                'updated_at' => '2023-02-04 22:59:08',
                'regency' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Roni Sudarmawan',
                'email' => 'roni@gmail.com',
                'password' => '$2y$10$xQmEWHDY9fNMAshH.O3zl.4rbXiUNc4QYlla4I2DJApgWaCuS6SUC',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:01:08',
                'updated_at' => '2023-02-04 23:01:08',
                'regency' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Mywear Thrifting',
                'email' => 'mywear@gmail.com',
                'password' => '$2y$10$AX5EFlCUQAcovTnVjS2CgOzlFJ.bRXZO78.6Ez9RvM553NjjA77Ca',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:14:54',
                'updated_at' => '2023-02-04 23:14:54',
                'regency' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Bali Thrift Shop',
                'email' => 'thriftshp@gmail.com',
                'password' => '$2y$10$T7lDH1u5cko9UZrwLCe0i.IJuHIBAnEMPXE2NGDRkpHJ9pm4pzW2q',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:17:02',
                'updated_at' => '2023-02-04 23:17:02',
                'regency' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Shine Hold Denim Store',
                'email' => 'shine@gmail.com',
                'password' => '$2y$10$iAzSz3MPdt/PfkHrDOYXM.ZBJaHECYcawzkyUzTJ0VS7EDGqIRnNy',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:19:45',
                'updated_at' => '2023-02-04 23:19:45',
                'regency' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Secondmate Thrift Shop',
                'email' => 'second@gmail.com',
                'password' => '$2y$10$kkU1rCYxI4VyxjInd5fV5OiwR/rtEbIKjOOqicveeCZfUN.zukocu',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:22:52',
                'updated_at' => '2023-02-04 23:22:52',
                'regency' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Reuser Stuff',
                'email' => 'reuser@gmail.com',
                'password' => '$2y$10$8.VnQmc37LFiq6fsxxBoL.RoH5hRSCbVZ/0fO18q0CHfOW1wK29DW',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:27:01',
                'updated_at' => '2023-02-04 23:27:01',
                'regency' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Fresh Second Stuff',
                'email' => 'fresh@gmail.com',
                'password' => '$2y$10$4tL1o.xjsfxbEgprM/Zy4OVjCeCsi9m2zWlAcQRnPHAhd32UJ7mNm',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:30:04',
                'updated_at' => '2023-02-04 23:30:04',
                'regency' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Thriftshop Murah',
                'email' => 'murah@gmail.com',
                'password' => '$2y$10$SQlXthOzbG3MPC4QQhckJu/.SmFqRXKOoEHyoIWlRRlzhmMXZ.vTK',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:35:52',
                'updated_at' => '2023-02-04 23:35:52',
                'regency' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Keranjangpria homestore',
                'email' => 'keranjang@gmail.com',
                'password' => '$2y$10$DzKlpTXCD1gmxm8AHkpTMu0nFW50CMgXfpYli.ZQHekTvgH8QIxk6',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:38:56',
                'updated_at' => '2023-02-04 23:38:56',
                'regency' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Kimmy Thrift',
                'email' => 'kimmy@gmail.com',
                'password' => '$2y$10$NS6iRzNIavx9lTRyUC4t9uGoRo0gGnjEoGgneTAiA1sZevIVWgi3m',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:41:04',
                'updated_at' => '2023-02-04 23:41:04',
                'regency' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => '30rabs Thrift Store',
                'email' => 'store@gmail.com',
                'password' => '$2y$10$dLQOi8cTpRAR6SgAk2bTTekXE7CFizgX8kwMz3XCxgWRKkUDpuoya',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:45:14',
                'updated_at' => '2023-02-04 23:45:14',
                'regency' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Chill Second Hand',
                'email' => 'chill@gmail.com',
                'password' => '$2y$10$bJcTs3PBRYOmjcYDFfRKuO1m4ufWDvTDnHLj0eq5mhFfbU9tnWSni',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:47:34',
                'updated_at' => '2023-02-04 23:47:34',
                'regency' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Preloved tri',
                'email' => 'preloved@gmail.com',
                'password' => '$2y$10$dIvA5dFuNwdTtfQvk.KsGuAY27NyEVRQLlKffv82kc9HXk2X5FmuS',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:49:05',
                'updated_at' => '2023-02-04 23:49:05',
                'regency' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Mokastuffs',
                'email' => 'mokas@gmail.com',
                'password' => '$2y$10$PJlUx59oaDlBE2PCREPZBeMf0WdlzgpSF2MQMHm2Z9qqA1JyYsiFa',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:52:41',
                'updated_at' => '2023-02-04 23:52:41',
                'regency' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Thrift Garage',
                'email' => 'garage@gmail.com',
                'password' => '$2y$10$Gg77vO4Qb.IEojk15NZHzuGpgrwn19wnOE/8gKBNNlSKkfuBReWL2',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:54:57',
                'updated_at' => '2023-02-04 23:54:57',
                'regency' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Bali Thrift Zone',
                'email' => 'zonee@gmail.com',
                'password' => '$2y$10$GO99.riZoNnZL4W1QKBVAOPKPHaJewzrfeZ/thwrpNdHzRyG5lmiW',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-04 23:57:00',
                'updated_at' => '2023-02-04 23:57:00',
                'regency' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Cantika Meisa',
                'email' => 'cantika@gmail.com',
                'password' => '$2y$10$n6os60cxwR0dNXrPWnrmDOhfY5GnjZCkX86qEIQug89FM41UhmjPu',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:00:25',
                'updated_at' => '2023-02-05 00:00:25',
                'regency' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Ghiffargo',
                'email' => 'fargo@gmail.com',
                'password' => '$2y$10$iJPhS3QfPEZIJrEktfcfeuE31ABzhBzmFz64R5/s0M9Rz/9gsGurK',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:01:55',
                'updated_at' => '2023-02-05 00:01:55',
                'regency' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Putu Vivia',
                'email' => 'vivia@gmail.com',
                'password' => '$2y$10$Ivfj7zwNj82NInPK.54l4uTgvQOJcIjhgfpuYGtwIH0ERtz793pjq',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:02:53',
                'updated_at' => '2023-02-05 00:02:53',
                'regency' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Adi Palguna',
                'email' => 'yande@gmail.com',
                'password' => '$2y$10$QYAoJhKKZL4SUP7vXq05meq3vPEF3juKI1/T3uw6ZR.aqKRBPXyle',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:03:39',
                'updated_at' => '2023-02-05 00:03:39',
                'regency' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Udha Yasa',
                'email' => 'udhayasa@gmail.com',
                'password' => '$2y$10$mdw6y9Pkxtemo.dBXSiTDebpnLAT0m0NWAwmIRTIPj4p2HVtioGHK',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:04:11',
                'updated_at' => '2023-02-05 00:04:11',
                'regency' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Wayan Pande',
                'email' => 'pande@gmail.com',
                'password' => '$2y$10$O4Ui.QxtGfMUYK23cAsfU.l6q/H0W.XC4TLJGGcQ.xO1WUVvwn7By',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:04:32',
                'updated_at' => '2023-02-05 00:04:32',
                'regency' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Fitri Hidayah',
                'email' => 'Fitri@gmail.com',
                'password' => '$2y$10$v/D6pbFeN0Mg6nmvP5IJXevB1hGw8wp5DzcgIyVLkQRnb/bWF20W.',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 00:04:56',
                'updated_at' => '2023-02-05 00:04:56',
                'regency' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Zulfa',
                'email' => 'zulfa@gmail.com',
                'password' => '$2y$10$.KIwiSIgKDnX/i/GJ3.oEuEa4fB2rqZ8BhyH1iBj/tagQPcFh3p4.',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-05 04:26:28',
                'updated_at' => '2023-02-05 04:26:28',
                'regency' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Melan',
                'email' => 'melan@gmail.com',
                'password' => '$2y$10$PLVpw1ZS62vAkUfPxqSZUOq5F9zJmhyeVwXPu9.Dx/xapb80xmzMu',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-07 16:34:33',
                'updated_at' => '2023-02-07 16:34:33',
                'regency' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$WxW9ep.98VSSXNgg5f0CBOHL3K5FLijbr9bZtMOMvOPhK/l6yZvx6',
                'phone' => NULL,
                'age' => NULL,
                'gender' => NULL,
                'address' => NULL,
                'created_at' => '2023-02-08 04:19:14',
                'updated_at' => '2023-02-08 04:19:14',
                'regency' => NULL,
            ),
        ));
        
        
    }
}